version: '3.8'

services:
  blastify-fe-revamp:
    image: ibobdb/blastify-fe-revamp:v0.1.0
    container_name: blastify-fe-revamp
    restart: unless-stopped
    volumes:
      - /var/log/blastify-fe:/app/logs
    ports:
      - '5000:5000'
    environment:
      TZ: Asia/Jakarta
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    networks:
      - caddy_network

networks:
  caddy_network:
    external: true
