name: Docker Build and Push

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get-latest-tag.outputs.tag }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Latest Tag
        id: get-latest-tag
        run: |
          if git describe --tags --abbrev=0 > /dev/null 2>&1; then
            TAG=$(git describe --tags --abbrev=0)
            echo "LATEST_TAG=$TAG" >> $GITHUB_ENV
            echo "tag=$TAG" >> $GITHUB_OUTPUT
          else
            echo "LATEST_TAG=0.0.1" >> $GITHUB_ENV
            echo "tag=0.0.1" >> $GITHUB_OUTPUT
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/blastify-fe-revamp:${{ steps.get-latest-tag.outputs.tag }}
          build-args: |
            GIT_TAG=${{ steps.get-latest-tag.outputs.tag }}
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
            NEXT_PUBLIC_APP_NAME=${{ secrets.NEXT_PUBLIC_APP_NAME }}
            NEXT_PUBLIC_API_KEY=${{ secrets.NEXT_PUBLIC_API_KEY }}
            NEXT_PUBLIC_MIDTRANS_CLIENT_KEY=${{ secrets.NEXT_PUBLIC_MIDTRANS_CLIENT_KEY }}
      - name: Verify Environment Variables in Image
        run: |
          echo "Testing built image..."
          docker run --rm ${{ secrets.DOCKER_USERNAME }}/blastify-fe-revamp:${{ steps.get-latest-tag.outputs.tag }} env | grep NEXT_PUBLIC || echo "NEXT_PUBLIC secrets not found"

  blastify-notification:
    runs-on: ubuntu-latest
    needs: docker
    if: needs.docker.result == 'success'
    steps:
      - name: Send Docker build success notification
        env:
          BLASTIFY_API_KEY: ${{ secrets.BLASTIFY_API_KEY }}
        run: |
          CURRENT_TIME=$(date '+%Y-%m-%d %H:%M:%S UTC')

          echo "Sending notification to Blastify API..."

          RESPONSE=$(curl --location 'https://api.blastify.tech/api-keys/send-messages' \
          --header "x-api-key: ${BLASTIFY_API_KEY}" \
          --header 'Content-Type: application/json' \
          --data "{
            \"numbers\": [\"082169072681\"],
            \"content\": \"✅ Docker build berhasil!\\n\\n🏷️ Tag: ${{ needs.docker.outputs.tag }}\\n🚀 Repository: ${{ github.repository }}\\n📅 Waktu: ${CURRENT_TIME}\\n🔗 Commit: ${{ github.sha }}\"
          }" \
          --write-out "HTTPSTATUS:%{http_code}" \
          --silent \
          --output /tmp/response.json)

          HTTP_STATUS=$(echo $RESPONSE | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
          RESPONSE_BODY=$(cat /tmp/response.json)

          echo "HTTP Status: $HTTP_STATUS"
          echo "Response Body: $RESPONSE_BODY"

          if [ $HTTP_STATUS -eq 200 ] || [ $HTTP_STATUS -eq 201 ]; then
            echo "✅ Notification sent successfully!"
          else
            echo "❌ Failed to send notification. HTTP Status: $HTTP_STATUS"
            exit 1
          fi
